Traceback (most recent call last):
  File "D:\github\bstock\sendqywx.py", line 21, in <module>
    sendresult= str(result_days_up_one.put_viewrecommend())
  File "D:\github\bstock\result_days_up_one.py", line 135, in put_viewrecommend
    cur.execute(sql)
  File "C:\ProgramData\Miniconda3\envs\bstock\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "C:\ProgramData\Miniconda3\envs\bstock\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "C:\ProgramData\Miniconda3\envs\bstock\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\ProgramData\Miniconda3\envs\bstock\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "C:\ProgramData\Miniconda3\envs\bstock\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "C:\ProgramData\Miniconda3\envs\bstock\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "C:\ProgramData\Miniconda3\envs\bstock\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\ProgramData\Miniconda3\envs\bstock\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'vtext' at row 1")
